from __future__ import annotations

"""
main.py
-------
Entry point for the Aegis backend server.

Run in development:
    python main.py

Run in production:
    uvicorn src.api.app:app --host 0.0.0.0 --port 8000 --workers 4

Interactive API docs (auto-generated by FastAPI):
    http://localhost:8000/docs
"""

import uvicorn

if __name__ == "__main__" :
    """
    """
    uvicorn.run(

        "src.api.app:app",
        host="0.0.0.0",
        port=8000,
        reload=True,    # hot reload in dev — set to False in production
        log_level="info",
    
    )
    