from __future__ import annotations

"""
main.py
-------
Entry point for the Aegis backend server.

Run in development:
    python main.py

Run in production:
    uvicorn src.api.app:app --host 0.0.0.0 --port 8000 --workers 4

Interactive API docs (auto-generated by FastAPI):
    http://localhost:8000/docs
"""

import uvicorn

from app.core.config import get_settings


if __name__ == "__main__":

    settings = get_settings()

    uvicorn.run(

        "app.main:app",
        host=settings.host,
        port=settings.port,
        reload=settings.debug,
        log_level="debug" if settings.debug else "info",

    )
