from __future__ import annotations

from collections.abc import Callable
from typing import Protocol

from app.domain.trades.entities import (
    DiscTradeAggregate,
    DiscTradeFieldRecord,
    DiscTradeInstrumentRecord,
    DiscTradeLegRecord,
    DiscTradePremiumRecord,
    DiscTradeRecord,
    DiscTradeSettlementRecord,
    TradeMasterRecord,
    TradeTypeRecord,
)
from app.domain.trades.enums import TradeTypeCode


class TradeUnitOfWork(Protocol):
    def __enter__(self) -> "TradeUnitOfWork": ...
    def __exit__(self, exc_type, exc, tb) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...

    def list_trade_types(self, id_org: int) -> list[TradeTypeRecord]: ...
    def get_trade_type_by_code(self, id_org: int, code: TradeTypeCode) -> TradeTypeRecord: ...

    def next_id_spe(self, id_org: int) -> int: ...
    def next_id_trade(self, id_org: int) -> int: ...
    def next_id_leg(self, id_org: int) -> int: ...
    def next_id_instrument(self, id_org: int) -> int: ...
    def next_id_premium(self, id_org: int) -> int: ...
    def next_id_settlement(self, id_org: int) -> int: ...
    def next_id_field(self, id_org: int) -> int: ...

    def add_master_trade(self, trade: TradeMasterRecord) -> None: ...
    def add_disc_trade(self, trade: DiscTradeRecord) -> None: ...
    def add_disc_leg(self, leg: DiscTradeLegRecord) -> None: ...
    def add_disc_instrument(self, instrument: DiscTradeInstrumentRecord) -> None: ...
    def add_disc_premium(self, premium: DiscTradePremiumRecord) -> None: ...
    def add_disc_settlement(self, settlement: DiscTradeSettlementRecord) -> None: ...
    def add_disc_fields(self, fields: DiscTradeFieldRecord) -> None: ...

    def list_trades(self, id_org: int, accessible_fund_ids: list[int] | None = None) -> list[TradeMasterRecord]: ...
    def get_disc_trade(self, id_org: int, id_spe: int) -> DiscTradeAggregate | None: ...


TradeUnitOfWorkFactory = Callable[[], TradeUnitOfWork]
